services:
  api:
    build: .
    ports:
      - "8007:8000"
    volumes:
      - .:/book-management-service
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: book_management_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  book-management-service:
  postgres_data:
